#!/bin/bash
# GraphRAG Comparison - Commands Cheatsheet
# Copy and paste these commands to work with the comparison framework

echo "═══════════════════════════════════════════════════════════════════════"
echo "   GraphRAG Comparison Framework - Command Cheatsheet"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""

# VIEWING DOCUMENTATION
echo "📖 VIEW DOCUMENTATION"
echo "─────────────────────────────────────────────────────────────────────"
echo "Quick Reference (2 min):"
echo "  cat QUICK_REFERENCE.md"
echo ""
echo "ASCII Visual Summary (5 min):"
echo "  cat COMPARISON_SUMMARY.txt"
echo ""
echo "Detailed Comparison (30 min):"
echo "  cat GRAPHRAG_GNN_COMPARISON.md"
echo ""
echo "Implementation Steps (20 min):"
echo "  cat HOW_TO_COMPARE.md"
echo ""
echo "README Index:"
echo "  cat README_COMPARISON.md"
echo ""

# VIEWING REPORTS
echo "📊 VIEW REPORTS"
echo "─────────────────────────────────────────────────────────────────────"
echo "Interactive HTML Report (no setup needed):"
echo "  open evaluation_results.html      # macOS"
echo "  firefox evaluation_results.html   # Linux"
echo "  xdg-open evaluation_results.html  # Linux (alternative)"
echo "  start evaluation_results.html     # Windows"
echo ""
echo "PDF Report (requires LaTeX):"
echo "  pdflatex evaluation_results.tex && open evaluation_results.pdf"
echo ""

# INSTALLATION
echo "⚙️  INSTALLATION"
echo "─────────────────────────────────────────────────────────────────────"
echo "Install GraphRAG+GNN dependencies:"
echo "  pip install torch torch-geometric"
echo ""
echo "Verify installation:"
echo "  python3 -c \"import torch; print('PyTorch OK'); import torch_geometric; print('torch-geometric OK')\""
echo ""

# RUNNING EVALUATIONS
echo "🚀 RUN EVALUATIONS"
echo "─────────────────────────────────────────────────────────────────────"
echo "Run all three approaches (45-60 min):"
echo "  python mitre_triple_evaluator.py"
echo ""
echo "Run with verbose output:"
echo "  python mitre_triple_evaluator.py --verbose"
echo ""
echo "Run with custom queries file:"
echo "  python mitre_triple_evaluator.py --queries my_queries.json"
echo ""
echo "Run and save results to custom file:"
echo "  python mitre_triple_evaluator.py --output my_results.json"
echo ""

# PYTHON USAGE
echo "🐍 PYTHON USAGE"
echo "─────────────────────────────────────────────────────────────────────"
echo "Use GraphRAG+GNN in your code:"
echo ""
echo "  from mitre_graphrag_gnn import GraphRAGGNNProcessor"
echo "  "
echo "  processor = GraphRAGGNNProcessor()"
echo "  result = processor.process_query('How is credential theft performed?')"
echo "  print(f'Processing time: {result.processing_time*1000:.2f}ms')"
echo "  print(f'Context: {result.context}')"
echo ""

# ANALYSIS COMMANDS
echo "📈 ANALYZE RESULTS"
echo "─────────────────────────────────────────────────────────────────────"
echo "View latest results (JSON):"
echo "  cat evaluation_results.json | python3 -m json.tool | less"
echo ""
echo "Count queries in results:"
echo "  cat evaluation_results.json | python3 -c \"import sys, json; print(len(json.load(sys.stdin)))\" queries"
echo ""
echo "Extract average scores:"
echo "  cat evaluation_results.json | python3 -c \"import sys, json; r=json.load(sys.stdin); print(f'RAG: {r['RAG_avg']:.2f}, Graph: {r['Graph_avg']:.2f}, GNN: {r['GNN_avg']:.2f}')\""
echo ""

# COMPARISON
echo "⚡ QUICK COMPARISON"
echo "─────────────────────────────────────────────────────────────────────"
echo "Side-by-side comparison:"
echo "  echo 'RAG: 7.87/10 (30-37s) | Graph+LLM: 7.16/10 (40-51s) | GraphRAG+GNN: 8.70/10 (60-120s)'"
echo ""

# FILE MANAGEMENT
echo "📁 FILE MANAGEMENT"
echo "─────────────────────────────────────────────────────────────────────"
echo "List all comparison files:"
echo "  ls -lh *COMPARISON* *GraphRAG* *README* *CHEATSHEET* evaluation_results.* 2>/dev/null | grep -v '.git'"
echo ""
echo "View file sizes:"
echo "  du -h README_COMPARISON.md GRAPHRAG_GNN_COMPARISON.md QUICK_REFERENCE.md HOW_TO_COMPARE.md"
echo ""
echo "Backup results:"
echo "  cp evaluation_results.json evaluation_results_backup_\$(date +%Y%m%d_%H%M%S).json"
echo ""

# SYSTEM CHECKS
echo "🔍 SYSTEM CHECKS"
echo "─────────────────────────────────────────────────────────────────────"
echo "Check Python version:"
echo "  python3 --version"
echo ""
echo "Check PyTorch:"
echo "  python3 -c \"import torch; print(f'PyTorch {torch.__version__}'); print(f'CUDA: {torch.cuda.is_available()}')\""
echo ""
echo "Check ArangoDB connection:"
echo "  curl -s http://localhost:8529/_api/version | python3 -m json.tool | head -5"
echo ""
echo "Check Ollama connection:"
echo "  curl -s http://localhost:11434/api/tags | python3 -m json.tool | head -10"
echo ""

# ADVANCED
echo "🔧 ADVANCED COMMANDS"
echo "─────────────────────────────────────────────────────────────────────"
echo "Run specific approach only (need to use Python directly):"
echo "  python3 -c \"from mitre_rag import RAGEvaluator; print('RAG loaded')\""
echo ""
echo "Update documentation:"
echo "  # Edit the .md files and re-render if needed"
echo ""
echo "Compare file sizes:"
echo "  du -h *.py *.md *.tex *.html | sort -h"
echo ""

# TROUBLESHOOTING
echo "❌ TROUBLESHOOTING"
echo "─────────────────────────────────────────────────────────────────────"
echo "If torch import fails:"
echo "  pip install --upgrade torch"
echo ""
echo "If torch-geometric import fails:"
echo "  pip install --upgrade torch-geometric"
echo ""
echo "If ArangoDB connection fails:"
echo "  # Check if running: docker ps | grep arangodb"
echo "  # Or: curl http://localhost:8529"
echo ""
echo "If Ollama connection fails:"
echo "  # Check if running: curl http://localhost:11434/api/tags"
echo ""

# HELP
echo "❓ HELP & DOCUMENTATION"
echo "─────────────────────────────────────────────────────────────────────"
echo "Get quick answers:"
echo "  cat QUICK_REFERENCE.md"
echo ""
echo "Understand the approaches:"
echo "  cat COMPARISON_SUMMARY.txt"
echo ""
echo "Step-by-step guide:"
echo "  cat HOW_TO_COMPARE.md"
echo ""
echo "Detailed technical info:"
echo "  cat GRAPHRAG_GNN_COMPARISON.md"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo "For more details, see: README_COMPARISON.md"
echo "═══════════════════════════════════════════════════════════════════════"
