#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   RAG vs Graph+LLM Evaluation Reports - Viewer                 ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Available reports:"
echo ""
echo "1️⃣  HTML Version (No Installation Needed)"
echo "   → evaluation_results.html"
echo "   → Open in any web browser"
echo "   → Responsive, interactive, styled"
echo ""
echo "2️⃣  LaTeX Source (Requires pdflatex)"
echo "   → evaluation_results.tex"
echo "   → For compilation to PDF"
echo "   → Professional academic format"
echo ""
echo "3️⃣  Raw Data (JSON)"
echo "   → batch_test_results.json"
echo "   → All evaluation scores and responses"
echo "   → For data analysis or integration"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 REPORT STATISTICS:"
echo ""
ls -lh /home/vasanthiyer-gpu/evaluation_results.* 2>/dev/null | awk '{print "   " $9 " (" $5 ")"}'
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 QUICK ACTIONS:"
echo ""
echo "   View HTML:  xdg-open /home/vasanthiyer-gpu/evaluation_results.html"
echo "   View JSON:  cat /home/vasanthiyer-gpu/batch_test_results.json | head -50"
echo "   Compile:    cd /home/vasanthiyer-gpu && pdflatex evaluation_results.tex"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
